// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwnafsfmwpcjtjlupldv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3bmFmc2Ztd3BjanRqbHVwbGR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NzcxODEsImV4cCI6MjA3MzI1MzE4MX0.MaQaCD16kKt1GFiysMc5zUYmMMPZZtfO6qPHRmCDn1M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});